### ISSUE TITLE
Stack Overflow staging for new questions gets double posted by SD after approval

### ISSUE THREAD

**Issue by Cowm00** [Charcoal-SE/SmokeDetector#11413]
### What problem has occurred? What issues has it caused?

Staging: https://m.erwaysoftware.com/posts/uid/stackoverflow/78579270
After approval: https://m.erwaysoftware.com/posts/uid/stackoverflow/78579301

### What would you like to happen/not happen?
I would like it to get posted once, but I'm not even sure if this is possible. This is more of a informative kind of thing in case someone doesn't know this happens.

**Comment by Spevacus** [comment]
Hmm. This is a tough one, because the IDs for the posts are different (first one is `https://stackoverflow.com/staging-ground/78579270`, second is `https://stackoverflow.com/questions/78579301`). When a question is published through the SG it basically makes a whole new question and just adds a timeline entry that it was posted via the SG (such as [this entry](https://stackoverflow.com/posts/78579301/timeline#history_93f8e70f-b43f-4963-983c-32c5ae447c87)).

I dunno. Another thing to consider is... Maybe this is acceptable behavior. One extra FP isn't the end of the world.

**Comment by Cowm00** [comment]
Ok, I understand, I just wanted to make sure, that you guys knew this was happening. :-)

**Comment by codygray** [comment]
I am in full agreement with what @Spevacus said. In fact, I'd go one step further: these are, effectively, completely different posts, so they *should* be separate reports. The Stack Overflow system treats them as two separate posts, as Spevacus already explained, and not only is it easier for us to continue to do the same, but I would argue that it is more correct.

From a system/implementation perspective, it is akin to a user deleting and then re-posting the exact same question. Their contents may be identical, and the second obviously originated from the first, but from Stack Overflow's perspective, they are two completely different posts, with two completely different histories.

It *might* be nice to have some kind of tracking that would link the second report ("proper" question) to the first report (Staging Ground question), but that would be quite difficult to implement, and not really worth doing, in my judgment. The genealogy is already available in the question's history, for those wanting to investigate. Reviewers of the report(s) do not need to see this connection in order to properly review.
