### ISSUE TITLE
Failures when performing blacklist operations should trigger a revert

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/SmokeDetector#1156]
Currently, if Smokey encounters a failure half way through the blacklist operation (e.g. a git push problem, master not up to date, etc), the operation will simply abort and continue from where it got up to. This means that Smokey gets stuck on the `master` branch (rather than `deploy`), and any commited blacklist changes will remain unpushed on master. This causes issues next time the command is used.

Instead, Smokey should automatically detect these failures, reset to the remote branch, switch back to deploy and continue as normal.

**Comment by teward** [comment]
I could have ***SWORN*** I had fixed this stuff before... I'll take a quick look at the code, I think I know where to fix this...

**Comment by teward** [comment]
The core of this should be fixed now with https://github.com/Charcoal-SE/SmokeDetector/commit/aa9c4c9d489890c3139acb7892b235d85709c823 but I left out a `return` code line which returns False if there's an error so we can report there was a git processing error of unknown cause.  I'm half-assing the code to make this bandaid *work* but it doesn't post to error logs currently.  (Maybe something to fix up later so it reports errors to a logged location?)

Waiting on https://github.com/Charcoal-SE/SmokeDetector/commit/02f328f915c47e1f7ef8ce205b9c75777d1d4dd3 to be captured as "CI Succeeded" then we can pull this.  Considering it fixed though, otherwise, since any git issues will just *fail* with an Exception in the code (resulting in hard-crash).

**Comment by teward** [comment]
Pulled into my Smokey instances, and also @bwDraco's Linode which is currently the active instance.  This should fix any git crash issues now; let's hope that's the case.  Waiting now for something to break, so we can see if we can close this  or not.

**Comment by iBug** [comment]
@teward Seems to have been working properly in the past year. Good to close this issue?
