### ISSUE TITLE
Many posts on Graphic Design and Astronomy didn't get caught today

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#1462]
Today's chat is full of `!!/report`s for questions which should've been caught automatically, even when accounting for the queue. Any idea what's going on?

https://metasmoke.erwaysoftware.com/search?reason=1

**Comment by surajrao** [comment]
Possibly related:  manual report on a post from Graphic Design did not work. SD responded as 

>  Could not find data for this post in the API. It may already have been deleted.

Transcript [here](https://chat.stackexchange.com/transcript/message/42150758#42150758)

**Comment by paper1111** [comment]
As seen in today's [transcript](https://chat.stackexchange.com/transcript/message/42193310#42193310), the post could not be reported until ~2 mins later, so the issue is probably that the SE API is not updated (and laggy), so the post could not be found in the API although it can be seen in the Websocket API and the questions page.

**Comment by Glorfindel83** [comment]
Here: https://chat.stackexchange.com/transcript/message/42193529#42193529 have I checked if the post was visible in the API before !!/reporting. It was, but still Smokey thought it didn't (or was it caching an earlier response?)

**Comment by CalvT** [comment]
Just a couple of random thoughts, but I think this might be caused by the following happening.

- A question/answer is posted
- Smokey gets the ID from the real-time page/websocket
- Requests details from the API about the ID
- The API is laggy atm, so the ID is not yet there.
- The API replies ID not found so Smokey moves on, missing the post

I'm not sure what could be done to fix this, but one idea was if Smokey can pull the title of the post along with the id, then run that title through findspam, and as a lot of spam titles are blatant, it could then report the id in the chatroom.

**Comment by quartata** [comment]
This is indeed what's happening (at least for automatic scanning). Smokey doesn't bother to check if every post it requires for in a batch got returned, just that it got anything back. If one or two posts are dropped, then they could have just been deleted after all.

**Comment by ArtOfCode-** [comment]
Fixed
