### ISSUE TITLE
Regression: "sd f" no longer deletes report in SOCVR

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#1475]
According to @jdd-software (PetterFriberg) who should know what to expect.

Chat link: https://chat.stackoverflow.com/transcript/message/40749725#40749725

(Uh, actually, the Smoke Detector message is not preserved in the chat transcript, so that link doesn't make a lot of sense.)

**Comment by tripleee** [comment]
Another Smoke Detector message *was* removed from the SOCVR chat just now when the referenced post was deleted.

https://chat.stackoverflow.com/transcript/message/40750493#40750493

**Comment by quartata** [comment]
Confused. Is it deleting or not deleting?

**Comment by quartata** [comment]
And did the fp feedback come from SOCVR or elsewhere?

**Comment by quartata** [comment]
As far as I'm aware, the behavior has always been fp feedback from that room -> deletes the report from that room. I can make it delete everywhere with some changes, but making it delete from MS feedback will be hard.

**Comment by jdd-software** [comment]
@quartata The feed back was from SOCVR room to a SD report in same room within message edit time window (like 30 s after sd message) it was a reply message f (not sd f, I need to test that). As far as I remember this feedback in same room (SOCVR) delete the SD report (which to me was nice, since that way you could avoid further traffic to post and maybe some accidental spam flagging). However I'm not room owner so I can't decided actually if this is desired behavior or not (I was just surprised it did not work anymore)

**Comment by tripleee** [comment]
So it deletes some _other_ messages (the basic delete functionality is fine) but this particular category of message is not being deleted.

**Comment by tripleee** [comment]
I see no recent changes in SOCVR behavior for the chat functionality and deletion requests, though I simply went over commit messages going back to April (which is when I am reasonably confident I still had a reasonable grasp of this part of the code) so I don't think we need to be afraid that this behavior was changed in the recent past before the chat refactoring.

**Comment by makyen** [comment]
SD was deleting upon `sd f` when posted within the 2 minute edit/delete window as recently as 2017-12-08T16:09:24.000Z ([Deleted SD Report](//chat.stackoverflow.com/transcript/41570?m=40372707#40372707) (not visible in displayed chat transcript) [the `sd f`](//chat.stackoverflow.com/transcript/41570?m=40372721#40372721)).

Looking at older SD reports where an `sd f` was sent as the next post (at least that hasn't been moved), there are [some occurrences back to March 2017](//chat.stackoverflow.com/transcript/41570?m=36372761#36372761) (as far back as I checked) where the SD report was not deleted. However, almost all SD reports were deleted when the `sd f` was within the edit/delete window.

The issue could be timing, or a difference in the time between when SD/MS thinks the post was made to chat and when SE thinks it happened (e.g. clock drift).

If there was a logic change (instead of a timing change), it was likely after 2017-12-01, but there really aren't enough data points to be sure when a change occurred (given that there are some older occurrences).
