### ISSUE TITLE
Do not notify me when not in chat

### ISSUE THREAD

**Issue by GrumpyCrouton** [Charcoal-SE/SmokeDetector#1636]
Please please please add the functionality for the bot to not send me notifications for things when I am not active in chat. Once I get off for the day, I get on the next day to 50+, sometimes 80+ notifications that I can do nothing with.

I know this is possibly, as [Natty](https://github.com/SOBotics/Natty/tree/master/src/main/java/in/bhargavrao/stackoverflow/natty) does it. I tried looking around in Natty's source code to figure out how it is done, but I am not familiar with bots or the notification systems in general for StackOverflow.

![image](https://user-images.githubusercontent.com/12193403/36483391-97cc529a-16db-11e8-9001-489df3015aee.png)

![image](https://user-images.githubusercontent.com/12193403/36483409-a4ce3986-16db-11e8-8201-76fff7d0bae0.png)

**Comment by pbdevch** [comment]
+1  
I would like such a feature too. AFAIK, [Queen in SOBotics](https://chat.stackoverflow.com/transcript/message/41339587#41339587) does that as well (for Heat Detector's messages).

**Comment by paper1111** [comment]
IIRC Natty and Queen pings only if you are in the room while Smokey pings all the time.

**Comment by ferrybig** [comment]
If this is going to be implemented, *I think* it should be on a per user basis.

I can image users who want to receive all notifications (For example mods who want to review everything that is flagged on their site)

I can image users who want to receive notifications when they are away (because then they cannot use user scripts that give them more detailed messages)

I can image users who want to receive notifications when they are inside the room, because that is the way they receive desktop notifications

**Comment by quartata** [comment]
This is a tough balance because for most notifications we (Charcoal regulars) want to be always notified. It's just for the high traffic sites like SO where it's annoying.

You may want to use [this userscript instead](since all the reports in SOBotics are going to be from SO)](https://github.com/Charcoal-SE/userscripts/blob/master/spamtracker/spamtracker.user.js).

**Comment by Bhargav-Rao** [comment]
@GrumpyCrouton All the bots in Sobotics have the option to ping all the time as well, but the default is to notify only when in room. For Nat: Here's the [code](https://github.com/SOBotics/Natty/blob/7251d785d9a30bd2f6019914ac2c86aa6e0b9d7a/src/main/java/in/bhargavrao/stackoverflow/natty/clients/Runner.java#L40), and here's [the format for opting in](http://natty.sobotics.org/commands#opt-in-command-format).

**Comment by GrumpyCrouton** [comment]
@quartata Well, it's hard to keep track of responses to things I've posted when my inbox is filled with notifications for things that _I can't even see anymore_, because usually by the next day the things reported by SmokeDetector have been removed already by the time I get on again.

@Bhargav-Rao Thank you!

@ferrybig  I agree it should be on a per-user basis. I think by default it should not notify you if you are not active, but you should be able to opt in, similar to [Natty](http://natty.sobotics.org/commands#opt-in-command-format).
