### ISSUE TITLE
Add the ability for users to retract manual reports in any room

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#1639]
Right now, if I file a report that is by mistake, others tell me that my report is improper, or the wrong post gets reported due to a bug (a current known bug is that the *question* sometimes get reported if an *answer* is reported as a full-form link), there's nothing much I can do, other than drop into Charcoal HQ from whatever other room I was using to file the report (N/A if the report was from CHQ itself) and reply to my own report saying that it's a false positive. Unfortunately, the report may spread to other rooms during that time, and it wastes others' time as they also have to flag the report as a false positive. 

As such, there should be the ability for users to retract their own manual reports, provided that no one has given feedback on them.

**Comment by quartata** [comment]
You can just use `delete-force`

**Comment by gparyani** [comment]
@quartata What if you didn't realize until more than two minutes later, after the time Smokey can delete its own messages? You can't use it then.

**Comment by angussidney** [comment]
The only way to 'retract' a post (other than marking it as FP which is sufficient enough IMO) is to delete the MS record. Currently only Undo and Art have the ability to do this, and even then we reserve it for exceptional circumstances.

**Comment by gparyani** [comment]
@angussidney So just to be clear here, you're considering this request declined? In that case, can you please clearly explain why each bit of my initial reason for implementing it is wrong? I know it sounds like a bit of a harsh request, but I'd legitimately like to know.

**Comment by ArtOfCode-** [comment]
Yeah, gonna call this declined. Actually _retracting_ a report (as in making it as if you never reported in the first place) is a lot of work to implement correctly - mostly on the MS side, where you have to remove not only the post record but anything that touches it; but also on the Smokey side, where we'd like to delete the message and any feedbacks to it, and drop it out of any lists that it got put in as a result of feedbacks or report.

Doing that amount of work is... not _entirely_ pointless, but given that we can apply a social solution that's much easier than the technical solution, I'd rather do that. So, steps to retracting a report:

 - Mark the report as an FP, preferably via a chat reply to Smokey rather than through MS so that you can add some explanation.
 - If _necessary_ ping Undo or me to remove the MS record. We tend to do that only for test/debugging reports, or for content so objectionable that we don't want it in the database (we have a database of literal spam, so that's a high bar to hit - think child porn, we've deleted a couple of those before).
 - Use `delete-force` if you're in the 2-minute window; if you're after that but you still want the message deleted, ping a Charcoal-local mod.

**Comment by angussidney** [comment]
> Actually retracting a report (as in making it as if you never reported in the first place) is a lot of work to implement correctly - mostly on the MS side, where you have to remove not only the post record but anything that touches it; but also on the Smokey side, where we'd like to delete the message and any feedbacks to it, and drop it out of any lists that it got put in as a result of feedbacks or report.

Additionally, handling security requirements will be hard. If Smokey can trigger a record to be deleted, then anyone with the SmokeDetector runner privilege will also be able to trigger a record to be deleted, an ability which is restricted to Developers (Art and Undo)

But apart from that.... what Art said. I don't necessarily disagree with the premise of your request, but rather I don't see how all the required development work would be worth it for the few times that it would ever be used.

**Comment by teward** [comment]
Even though this is closed, I just want to reiterate (so that @gparyani reads this message), this has been once again marked as "Declined" (and [confirmed as such by @ArtOfCode- in CharcoalHQ](https://chat.stackexchange.com/transcript/message/43902981#43902981))
