### ISSUE TITLE
Feedback from the Charcoal Test room should not go into production Metasmoke

### ISSUE THREAD

**Issue by magisch** [Charcoal-SE/SmokeDetector#1717]
A request by triplee. Functionality for that currently doesn't exist, so it'll have to be implemented seperately.

**Comment by ArtOfCode-** [comment]
I'm gonna decline this. While I understand the premise that test stuff generally shouldn't be immortalized, Charcoal Test is more there just to keep inane stuff out of the way of CHQ rather than to be a true test environment. The work required to do this kinda outweighs the value we get for making it such an environment.
