### ISSUE TITLE
Revisit Blacklist guidelines

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector#1773]
This discussion relates to [this](https://metasmoke.erwaysoftware.com/post/108597) post, but it is only the a recent post to exhibit this behavior.

---

We are blacklisting URLs that are already being detected by other heuristics. This doubling up of the same reason is leading to artificially high post weights and automatic flags. 

I don't think we should be double dipping. It's misleading and hard to explain when others question us. (A similar discussion has already occurred regarding Keyboard in Title vs. Keyword in Body...it's probably in both, leading to double dipping again). It's also flagging posts that are border line but not spam, like the post above.

**Comment by tripleee** [comment]
One of the reasons we have overlap is when a specific domain was prevalent in spam but only triggered pattern-matching domain name, on the theory that we might change the patterns and then start missing stuff which we were previously happily detecting. But I agree that e.g. watch and blacklist should not overlap.

**Comment by teward** [comment]
@tripleee I'm confused, is this post asking about overlap between watch and blacklist, or overlap between the hard-coded regexes inside Smokey and the blacklist?  I agree the overlap between watchlist and everything else is major, but excluding watchlist which doesn't impact flag weights and autoflag triggers, the question boils down to the blacklist function specifically and us either rewriting how that blacklist function works or redoing the guidelines (the second of which is easier)

**Comment by CalvT** [comment]
I'm conflicted on this, as half of me has wanted for a long time to suggest implementing some kind of automated check on all blacklists to:
 
 - See if they are caught by a pattern.
 - See if they are getting too many fps.
 - See if there is a keyword and a website for the same thing.

And then potentially move them to watch, and alert in chat as to the change.

But then I agree with tripleee doubling up to autoflag known spammers, which with the above would not be possible.

**Comment by AWegnerGitHub** [comment]
@teward I am not asking about blacklist/watchlist overlap. I am asking about hard coded regexes and the blacklist.

**Comment by teward** [comment]
@AWegnerGitHub I was directing my comment to triplee, I know what *your* question was asking, I was asking clarification on tripleee's initial reply to you.

**Comment by AWegnerGitHub** [comment]
Another instance of double dipping - this time it's a true positive:

https://metasmoke.erwaysoftware.com/post/110826

We hit `erectentry` on three reasons.

**Comment by tripleee** [comment]
(Actually that's "URL in title" and then the blacklisted domain name in the title and in the body.)

**Comment by FYPetro** [comment]
Reasons are currently weighted separately by their accuracy. Correlation among different reasons causes double tripping (even worse, triple-dipping). If we have statistics on the correlation among the reasons of which a post is caught, these statistics should contain information on how to correctly weigh the individual weights.

Suppose a post is caught with 3 reasons, A (90%), B (90%), and C (60%) and the correlation matrix of the three reasons are

|    | A | B | C |
| -- | -- | -- | -- |
| A | 100% | 0% | 0% |
| B | 0% | 100% | 0% |
| C | 0% | 0% | 100% |

Then we're confident that the three reasons are linearly independent with one another and the post should carry the total weight 90+90+60=240.  However, suppose that the correlation matrix is

|    | A | B | C |
| -- | -- | -- | -- |
| A | 100% | 100% | 0% |
| B | 100% | 100% | 0% |
| C | 0% | 0% | 100% |

Then we know that reasons A and B are 100% correlated and the total weight should be 150 instead of the full 240. There is some statistics going on that should tell us how to get 150.

Do you think this idea based on statistics is sound enough?
