### ISSUE TITLE
Allow users who manually report posts to specify an optional reason to be posted in Smokey's message

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#1965]
I'd like to propose a new feature for SmokeDetector, to allow users who file manual reports to specify an optional reason when doing so. Manual reports are usually filed because the post is still spam, but evaded Smokey's spam heuristics. Occasionally, it may also not be obvious to other humans that it's in fact spam. For example, [this report](https://chat.stackexchange.com/transcript/message/43834039#43834039) for a spam seed, which other users giving feedback in other chat rooms may not know is a spam seed unless they bothered to go into Charcoal HQ and look it up.

Implementing this would allow the reporter to supply a reason indicating that the post is a spam seed, which would be shown in the metasmoke page for the manual report, and in Smokey's messages in all chat rooms.

In my mind, this would look like this:

    !!/report [link] "[reason]" [link] "[reason]"...

An example report would be:

    !!/report https://meta.stackexchange.com/q/3122 "PST repair spam"

**Comment by teward** [comment]
## Summary:

I think this is doable, but the amount of complexity we'll have to have in the processing logic for this will make the code coverage/complexity *much* higher than we would probably like.

Technical details on the implementation are below, *but they do not take into consideration whether MetaSmoke will have any issues with this implementation*.

------

------

## Implementation Data

In `chatcommands.py`, the Report command (currently on line #1057) has a function declaration like this:

    def report(msg, urls):

... from which we then create a list of URLs inside (on line 1073) with:

    urls = list(set(urls.split()))

This set of URLs, then, is iterated over via a `for` loop as:

    for index, url in enumerate(urls, start=1)

... of which each tuple that is returned by `enumerate` is processed via the single index value for the loop and the URL for report processing.

Therefore, the way this is passed in is that we explicitly take *all* the arguments sent via `!!/report` and then use that to populate the `urls` argument that is passed during the call of the `report` command by splitting on space-delimitation (i.e. "foo bar baz" being the arguments run through a `.split()` will return the list of `["foo", "bar", "baz"]` with the way we're doing the current URL list population).

From SmokeDetector's point of view, this is easily doable, at least for splitting these cases down.  Now, there are four specific cases I look at and build upon, and we're assuming that `msgargs` is going to have all the arguments that were passed to the `report` function as part of its declaration, and we'll build 'reports' instead of URLs:

------

**Case 1: Multiple URLs being reported, each with its own defined reason**: *Doable, but not nice*

Let's take a look at your first case, operating under the assumption that puts a specific reason for each report.  A call of `!!/report foo.com/fudge "bar baz" foo.com/yay "foo bar"` would end up with `msgargs` passed into such redefined function as this string: `foo.com/fudge "bar baz" foo.com/yay "foo bar"`

Let's take that and preprocess it (assume that `msgargs` is the variable in the function definition):

    reports = []
    reportraw = msgargs.split('" ')
    for report in reportraw:
        reportdata = report.split(' "')
        reports.append((reportdata[0],reportdata[1]))

... will have a `reports` object containing tuples, which ends up like this *the 'pretty print' is my doing):

    [('foo.com/fudge', 'bar baz'),
     ('foo.com/yay', 'foo bar"')]

... whereby each tuple can be handled properly.  This is able to be *handled*, but not very kindly in loops (the handling of which is irrelevant here for now).

------

**Case 2: A single URL is reported without a reason.**

Now, let's look at your second case.  The above code works, but we need to adjust it little for a bare `!!/report foo.com/fudge` call to handle there not being a quote character in it:

    reports = []
    reportraw = msgargs.split('" ')
    for report in reportraw:
        if '"' in report:
            reportdata = report.split(' "')
            reportdata[1] = reportdata[1].replace('"', '')
            reports.append((reportdata[0],reportdata[1]))
        else:
            reports.append((report, None))

------

**Case 3: Multiple URLs with a single report reason at the end**:

This would happen if `!!/report url1 url2 url3 "global report reason for all"` happens, as the `reportraw` value would be `['foo.com/one foo.com/fudge "bar baz"']`.

Now, *this* we can do, but the above code wouldn't work for it.  *For just this case*, the split code is:

    reports = []
    reportraw = msgargs.split('" ')
    for report in reportraw:
        reportdata = report.split(' "')
        reportdata[1] = reportdata[1].replace('"', '')
        if ' ' in reportdata[0]:
            reporturls = reportdata[0].split()
            for url in reporturls:
                reports.append((url, reportdata[1].replace('"','')))
        else:
            reports.append((reportdata[0], reportdata[1].replace('"','')))

... and the resultant `reports` are:

    [('foo.com/one', 'bar baz'),
     ('foo.com/fudge', 'bar baz')]

And this is usable and doable.

------

**Case 4: Multiple URLs, but each URL does *not* have an explicit reason set next to it**

Now, this is the truly evil case.  We basically have to hybridize all the cases together and have a really *evil* bit of code.

Assume someone does this with `!!/report foo.com/one foo.com/fudge "bar baz" foo.com/yay "foo bar"`, which is entirely possible.

`reportraw` would end up being this:

    ['foo.com/one foo.com/fudge "bar baz', 'foo.com/yay "foo bar"']

... and then when we try and split this down further using the rest of the script, `reports` ends up as:

    [('foo.com/one foo.com/fudge', 'bar baz'),
     ('foo.com/yay', 'foo bar"')]

So now, we have to do an iterative version of the processing that Case 3 has:

    reports = []
    reportraw = msgargs.split('" ')
    for report in reportraw:
        if '"' in report:
            reportdata = report.split(' "')
            reportdata[1] = reportdata[1].replace('"', '')
            if ' ' in reportdata[0]:
                reporturls = reportdata[0].split()
                for url in reporturls:
                    reports.append((url, reportdata[1]))
            else:
                reports.append((reportdata[0], reportdata[1]))
        else:
            reports.append((report, None))

Just keep in mind how complicated this logic got.  And how quickly, nonetheless.

------

Assuming we have the code from the last test-case, then *in theory* instead of looping over the `for url in enumerate(urls, start=1):` that we had for processing, we'd instead have to do `for report in enumerate(reports, start=1):`, and then **change the behavior for this loop**, such that the loop at line 1081 becomes:

    for index, report in enumerate(reports, start=1):
        url = rebuild_url(report[0])
        post = api_get_post(url)
        reason = report[1]
        
        ...  # The rest of the code is otherwise the same until we get to line 1119 in the existing code...
        
        if reason:
            why_info = u"Post manually reported by user *{}* in room *{}* with reason *'{}'*.\n".format(msg.owner.name, msg.room.name, reason)
        else:
            why_info = u"Post manually reported by user *{}* in room *{}*.\n".format(msg.owner.name, msg.room.name)
        
        ... # The rest of the code for the function is the same.

This is doable.  But this doesn't take into consideration how MetaSmoke handles this report.

**Comment by teward** [comment]
@ArtOfCode- or @Undo1:

I'd like your input on the above, before we even begin attempting implementation of this.  It *is* doable, but whether we need this or not is a question that I would like one of you to review both for whether this is needed, and whether MetaSmoke will complain about these changes when it sees the reasons.

**Comment by teward** [comment]
NOTE on implementation that wherever we get the URLs passed into the report function could do the preprocessing steps, too, but the increase in code logic and complexity will still be substantial regardless

**Comment by AWegnerGitHub** [comment]
My opinion: only implement cases 2 (which is how it is now) and 3. Either no reason or one reason for all URLs. If someone wants separate reasons for their reports, then issues multiple commands with individual reasons. 

This reduces code complexity and syntax needed to issue a command. As much as we like to star commands of multiple reports due to their complexity, it is error prone. This will be the same. I prefer to not allow that complexity.

**Comment by quartata** [comment]
Yeah, you shouldn't do a batch report of posts that aren't related to each other in some way

**Comment by teward** [comment]
I agree on implementing both cases 2 and 3, in that we only accept the following cases:

    !!/report URL
    !!/report URL1 URL2
    !!/report URL "Reason Here"
    !!/report URL1 URL2 "Reason Here"

This covers both the existing functionalities, and just adds reason processing on top of it (rather than all 4 of the test cases I provided in my longer post, as I was only including 'new' functionality in that post)

But, I think we need a little more info on how MS is going to handle the report when it's handed off to the backend to be processed... that's really key here.  We can always handle splitting of URLs and reason(s) to before we receive data in the `report` command, so that when we're parsing the data to pass that happens.

**Comment by teward** [comment]
@quartata brought up a good point, "What if someone includes ` "` in the reason itself?" and that there may be a user or two having issues here.

The logic I wrote would still work, but instead of making tuples for handling, we'd just split out the urls *and* the reasons, and then do `reason = ' "'.join(reportraw[1:])` which would work then, but there's a few potential ways to implement.  I'll draw up some code for consideration in a separate branch, then include it here for consideration.

**Comment by AWegnerGitHub** [comment]
Wait...are we having these reasons as official MS reasons or just using
them to give to Smokey to provide context when it reposts the link
elsewhere?

Saving these reasons sounds like a horrible idea. They won't be
standardized and will have typos, capitalization differences, etc. I bet
you given just a bit of time we could also find an exploit.

**Comment by teward** [comment]
@AWegnerGitHub No.  This 'why' reason is only passed to MetaSmoke and only shows if you do a `why` response to the specific report message.

But we can test this too, before we incorporate to make sure this is the case.  I'll just have Undo clear out the MS report test cases for the tested items after the tests.

**Comment by teward** [comment]
@AWegnerGitHub We just tested this on TCOM ("The Call of Midnight", the unique Test System case for my dev instance), and reports still showed as https://chat.stackexchange.com/transcript/message/43855979#43855979 which is this 'raw' message posted in the chat room:

    [ [SmokeDetector](//goo.gl/eLDYqh) | [MS](//m.erwaysoftware.com/posts/by-url?url=//askubuntu.com/questions/34978) ] Manually reported question (batch report: post 2 out of 2): [Configuring to detect if a command does not exist, suggest installation](//askubuntu.com/questions/34978) by [Thomas Ward](//askubuntu.com/users/10616) on `askubuntu.com`

This worked fine.

**Comment by gparyani** [comment]
I'd be fine with `!!/report [link 1] [more links...] "[global reason]"`.

**Comment by teward** [comment]
Regarding posting the reason in all the chat rooms as part of the "Manually reported" posts, I disagree with that being done, because it requires chat messages to be properly formatted, with grammar, etc. being pretty darn perfect. and depending on the length of the custom reason, it could be an issue with chat limits or formatting.  I believe the 'why' response to a message to get details is sufficient enough a method to get the custom reasons, and I dont think this should be expanded to adjust the message sent to all relevant chat rooms on a manual report, as everyone uses the why response command normally, anyways, even on standard capture reasons for details on the report reason/detection.

**Comment by gparyani** [comment]
The above commit was merged, so this has been implemented. Thanks @ArtOfCode- . Closing.
