### ISSUE TITLE
Requesting push access to this repository (SmokeDetector)

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#2252]
After [my first PR to code base][2] on Jan 3, 2018, I have contributed to Smokey's code base to an extent. I think I have a decent understanding of Smokey's code as of now and is potentially a good developer of Smokey.

Therefore, I think it'd be good if I can have push access to this repository. I will use it to:

- Modify blacklist files
- Applying trivial or urgent updates and fixes directly (like [this one][3])
- Approve and merge PRs from others
- Merge approved PRs from myself

When unsure, I will continue to submit PRs and wait for reviews before pushing to the repo.

[Here are all the jobs I've done][1]. Thank you for your support.

[1]: https://github.com/Charcoal-SE/SmokeDetector/pulls?q=author%3Aibug
[2]: https://github.com/Charcoal-SE/SmokeDetector/pull/1441
[3]: https://github.com/Charcoal-SE/SmokeDetector/pull/2250

**Comment by angussidney** [comment]
It's a thumbs up from me 👍 

Only one thing: I know that you use your phone fairly often for development. When I first heard about this, I was concerned that the nature of the device would lead to many mistakes. However, you have since familiarised me with your workflow, and I'm confident that it won't be a major issue. 

But just to reiterate, if you gain push access your commits will go straight through, so you'll need to be especially sure that your code is free of mistakes before direct pushing. For larger changes (e.g. refactorings, new commands/features), we tend to use PRs anyway, as it allows someone else to review the change before it is merged.

**Comment by iBug** [comment]
@angussidney Thanks for the comment. I have `origin` point to my fork everywhere and `upstream` to this repo, so I will always push to my fork with `git push`. My workflow in the future will most likely be pushing to my fork → fix Travis CI (if any) → merge, rebase and push to upstream.

**Comment by angussidney** [comment]
https://chat.stackexchange.com/transcript/message/45129898#45129898
