### ISSUE TITLE
Shall we enable Smokey to pull from force-pushes?

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#2561]
Currently Smokey's pulling only uses `git-pull`, and as a consequence some related checks are in place, for example ensuring the target can be fast-forwarded before pulling.

This method apparently can't handle non-ff cases, like a force push.

Given that all modified files (logs, config, etc.) are ignored in `.gitignore`, we can probably use this method to allow pulling through force pushes:

```
git reset --hard origin/deploy
```

Is it going to be something handy to have?

**Comment by angussidney** [comment]
Generally, there are only three reasons why a force push occurs: 

1. There's a deploy/master mixup due to a mistake when setting up a new smokey (in which case, the host is directly on hand to fix the issue)
2. A developer accidentally pushes to the wrong branch (in which case, it hasn't been pulled yet)
3. Something really bad went wrong, in which case we probably don't want to perform git surgery via Smokey commands (manual intervention would be more appropriate)

I don't see how this command would be useful for any of those scenarios. What usecase were you considering for the command?

**Comment by iBug** [comment]
Result: This is going to be useless.
