### ISSUE TITLE
Unwatch NS cloudns.net?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#2683]
https://metasmoke.erwaysoftware.com/search?feedback_filter=tp&utf8=%E2%9C%93&why=cloudns.net has a good number of 1-score spam which would otherwise not be detected, but the FP rate is high (currently 21/94). Figure out if there is something we could do to reduce the FPs and still keep watching, or maybe just remove the watch.

**Comment by double-beep** [comment]
I've proposed some watches to the ~15 1-score spam posts caught, so now, most of them will be caught for "Potentially bad keyword in body". The rest of the links have some hits in SE or have received some FPs lately, indicating that the spam with them has possibly stopped.

Since we catch 1~4 TPs per month and a couple of FPs (lately the stats are more awful), I suggest to unwatch `cloudns.net`.

**Comment by tripleee** [comment]
There was a recent flurry of TP posts but I watched the two domain names and will proceed to remove this NS watch now.

https://chat.stackexchange.com/transcript/message/50369552#50369552
