### ISSUE TITLE
GitHub username and password from config file are not set/used by SD instance

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/SmokeDetector#2743]
When I was setting up an SD instance, it was necessary to manually set, and cause git to persist, the username and password in the local directory which is the cloned repository. Without manually setting this, the various commands to SD which require authentication fail. This happens even though the correct `github_username` and `github_password` are already set in the SD config file located in the directory in which the SD instance is started.

**Comment by ArtOfCode-** [comment]
Smokey needs both to be set to function correctly - `git config` commands to set things so that it can make commits, and fields in `config` that it can use to authenticate to the GH API.

**Comment by makyen** [comment]
I can understand that. A reasonable way to resolve this is to document it. At the moment, our documentation for setting up an SD instance doesn't cover the need to manually cause the repo to always use the SD username and password, but does cover the need to set the `git config` `user.email` and `user.name` (these are separate things from what this issue is about).

In addition, it's arguably inappropriate to leave the repo, or git for that system-user globally, set to always use the SD credentials (not the email/username, but the username/password), considering that people might make changes in the repo and mistakenly attempt to commit a change under the SD username/email address.

In addition, it would be preferable to have the GitHub username and password only located in one place (e.g. the config file), rather than it being necessary to manually copy it to another location.

**Comment by iBug** [comment]
What I can tell, Smokey always commits using its identity (it calls `git commit --author="author information"`), which is written in code and does not depend on `config`. However, the option `--author=` cannot bypass Git's requirement of setting committer information in either repo-local `.git/config` or user-global (`$HOME/.gitconfig`). The `git config` commands in the setup guide pretty much covers this Git's requirement, rather than Smokey's behavior.

Rest assured, the GH username and email is only used when creating PRs (authenticating with GH API) and is likely replaceable with an access token or some other kind of API key.

**Comment by makyen** [comment]
This was resolved/fixed with [commit 93e3edfd](https://github.com/Charcoal-SE/SmokeDetector/commit/93e3edfd2faadeab7fc15e21d29e258ef2cfe189).
