### ISSUE TITLE
Add support to SD for threaded conversations

### ISSUE THREAD

**Issue by Tyler-H** [Charcoal-SE/SmokeDetector#2807]
SmokeDetector will often post an alert for a message with a bad keyword that isn't immediately obvious/discoverable upon reading the post... so we ask SD why and it will respond. Out of habit, I (and I'm sure some others) often reply with "tp" or "fp" to SD's second message, to which it responds by saying "this is not a report". 

My request is that SD should really understand conversation threading  (at least one round of it), so that the following threaded reply conversation works:
 
- Msg1 (original report) - SD: report
- Msg2 (Reply to Msg1) - Me: why
- Msg3 (Reply to Msg2) - SD: keyword "`<keyword>`"
- Msg4 (Reply to Msg3) - Me: fp
- Msg5 (Reply to Msg4) - SD: post registered as a false positive

**Comment by ArtOfCode-** [comment]
Declining - the dev time this would take is out of proportion with the use it provides, given how much effort or takes to correct this kind of error.

**Comment by double-beep** [comment]
I fully disagree with that.

Your first problem is that you cannot easily see what are the keywords as of the reasons:

- Pontentially bad keyword in body.
- Bad keyword in body

etc.

This is solved by clicking the `MS` button next to `SmokeDetector` in each report. Thus, you can view the exact reasons, e.g.:

![image](https://user-images.githubusercontent.com/38133098/55242403-d7e76d00-5245-11e9-9f72-108c3b12a2cd.png)

Your second problem is that you'd like Smokey to know if you previously has commented `sd why`. This seems useless to me. `sd *` command checks for the last smoke detector chat message and runs the command in it. The solution here, is to use the `-` in order to skip messages. For example, if you want to skip 2 messages, use:

    sd 2- command

and so on (3 messages: `sd 3- *`).

So, I am with @ArtOfCode- and don't think this should be implemented.

**Comment by Tyler-H** [comment]
@double-beep Your reply doesn't really make much sense as a response to this request. I don't have a problem with using the why command, I have a problem with Smokey not supporting responses in a chained conversation. The feature I requested is agnostic of the type of report Smokey makes. ArtOfCode's rejection is for entirely different and sensible reasons (e.g. way too much work to implement given the current API).
