### ISSUE TITLE
Removal of Site from Blacklist

### ISSUE THREAD

**Issue by srisadhana** [Charcoal-SE/SmokeDetector#3329]
spiritualsadhana/.com is a secure site with many unique visitors daily.  Please consider removing from blacklist as there is no point of spam from its users.

https://github.com/Charcoal-SE/SmokeDetector/pull/431

**Comment by ArtOfCode-** [comment]
@srisadhana Please refer to our [blacklist removal policy](https://charcoal-se.org/smokey/Process-for-blacklist-removal).

 - You will need to demonstrate that you're a representative of this site.  
  This can be done by adding a DNS record to the domain; use a TXT record with a key of `charcoal` and a value of `gh-3329`. Once we've verified the record has been added, you can remove it again. If you're not able to do this, please let us know and we'll find another way.
 - You will also need to demonstrate that the site was not responsible for past spam attempts.  
  I'm willing to give you the benefit of the doubt here since there's no direct evidence that it _was_ responsible. However, the [news page](http://spiritualsadhana.com/news) on the site is _exactly_ the kind of content that was posted on Stack Exchange. I'd strongly advise removing that. I'd also advise you clarify the section on "Spammers" in your terms and conditions, because at the moment it's very unclear what you mean by that.

If you can demonstrate you're a representative of the site, I'll start the removal process, and the site will be demoted to the watchlist for 2 months; if we don't see any more spam in that time then it can be removed completely.

**Comment by ArtOfCode-** [comment]
No response in over a week. Closing this; we can reopen if necessary.

**Comment by srisadhana** [comment]
Hi Charcoal
I couldn't be able to add TXT record to my domain. Is there any way to verify it?

Sorry for the delayed response.

**Comment by ArtOfCode-** [comment]
@srisadhana Are you able to add the text `charcoal-gh-3329` somewhere on the website? Leave us a link here to where you've added it, and again once we've checked it you can remove it.

**Comment by srisadhana** [comment]
@ArtOfCode- please check this page [about us](http://spiritualsadhana.com/about-us/)

- I have updated [news page](http://spiritualsadhana.com/news/)

- Given clarification on "spammers" referred as per our site policy.

**Comment by ArtOfCode-** [comment]
@srisadhana Thanks, that's verified. I've demoted the site off the blacklist. It's still on the watchlist - it'll become eligible for removal from that as well in 2 months' time, so any time after 2019-12-05.
