### ISSUE TITLE
Exclude goo.gl/forms and goo.gl/maps from the short URL check

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#3720]
Yes, `goo.gl` is a URL shortener, and yes, I'm aware that it's been discontinued. I don't disagree that it should remain on the watchlist since old links still continue to work.

However, since (and before) its discontinuation, it has been repurposed to provide internal Google link shortcuts, e.g. `goo.gl/maps/...` and `goo.gl/forms/...`.

Can these, as well as any other legitimate Google-internal short URL schemes, please be removed from the short URL check?

**Comment by tripleee** [comment]
[goo.gl/forms](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=goo.gl%2Fforms) is 34/37 and many of the recent TPs trigger no other rule. (Well, none of them are strictly speaking recent, but anyway.) Do we really want to disable this just to add a separate watch for forms?

[goo.gl/maps](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=goo.gl%2Fmaps) is a more reasonable 7/24 where only one of those 7 TPs was caught solely because of this rule.

**Comment by gparyani** [comment]
Fixed in #3813
