### ISSUE TITLE
False positives on vs.*live regex(es?)

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#3966]
### What problem has occurred? What issues has it caused?

A couple of posts recently were reported which had triggered on something which was (a) hard to discover and pin down, and (b) definitely FP.

It looks like the regex for `vs` followed by `live` currently on line 1890 of `findspam.py` is problematic and FP-prone, and should be tightened up.

Discussion starts a short while after the first FP https://chat.stackexchange.com/transcript/message/54615485#54615485

### What would you like to happen/not happen?

Fix FPs as outlined in discussion.

**Comment by tripleee** [comment]
https://chat.stackexchange.com/transcript/11540?m=54615699#54615699 has a concrete proposal:

```
sed -i~ 's_\\bvs\\b\.\*\\b(live|vivo)\\b|(?<!can |uld )\\bwe offer\\b|payday loan|смотреть\.\*онлайн|_\\bvs\\b\.\*\\b(live|vivo)\\b|(?<!can |uld )\\bwe offer\\b|payday loan|смотреть\.{0,60}онлайн|_' findpam.py
```

**Comment by makyen** [comment]
There were multiple problems with this regex. Please see [my comment here](https://github.com/Charcoal-SE/SmokeDetector/pull/3973#issuecomment-648706092) for some of the issues.

The specific portion of the regex which this issue is about, was originally `\bvs\b.*\b(live|vivo)\b` which had (68%TP):
* [Title Results: 175/TP:119/FP:56/NAA:0](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title_is_regex=1&title=%5Cbvs%5Cb.*%5Cb%28live%7Cvivo%29%5Cb)
* [Username Results: 2/TP:2/FP:0/NAA:0](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&username_is_regex=1&username=%5Cbvs%5Cb.*%5Cb%28live%7Cvivo%29%5Cb)

I changed it to `\bvs\b(?![\W_]*+(?:code|mvc)\b).{0,150}\b(live|vivo)\b` which has (80%TP):
* [Title Results: 149/TP:119/FP:30/NAA:0](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title_is_regex=1&title=%5Cbvs%5Cb.*%5Cb%28live%7Cvivo%29%5Cb)
* [Username Results: 2/TP:2/FP:0/NAA:0](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&username_is_regex=1&username=%5Cbvs%5Cb.*%5Cb%28live%7Cvivo%29%5Cb)

However, even at 80%TP, it does not qualify to be on the blacklist. So, in addition to each sub-regex which didn't individually qualify for the blacklist, I moved it to a new watchlist definition which only looks at titles and usernames.

At the same time, I made performance improvements to the regexes and fixed one of the sub-regexes which was broken.

The resulting code is:

```python
# Bad keywords in titles and usernames, all sites
# %TP: 2020-06-27 01:00UTC: ~97.65%TP
# Title Results: 2925/TP:2864/FP:60/NAA:0
# Username Results: 54/TP:45/FP:6/NAA:3
create_rule("bad keyword in {}",
            r"(?i)"
            r"^(?:"
            "" r"(?=.{0,150}?\b(?:online|hd)\b)"
            "" r"(?=.{0,150}?(?:free|full|unlimited))"
            "" r".{0,150}?movies?\b"
            r")"
            r"|^(?=.{0,150}?skin).{0,150}(?:care|product)s?\b"
            r"|^(?=.{0,150}?packer).{0,150}mover"
            r"|(online|certification).{0,150}?training",
            title=True, body=False, username=True,
            max_rep=32, max_score=1)

# Potentially bad keywords in titles and usernames, all sites
# Not suffient %TP for blacklist: 2020-06-27 01:00UTC: ~77.59%TP
# Title Results: 398/TP:312/FP:81/NAA:3
# Username Results: 17/TP:10/FP:8/NAA:0
create_rule("potentially bad keyword in {}",
            r"(?i)"
            r"\bvs\b(?![\W_]*+(?:code|mvc)\b).{0,150}\b(live|vivo)\b"
            r"|\bwe offer(?<!(?:can |uld )we offer)\b"
            r"|payday[\W_]*+loan"
            r"|смотреть.{0,150}онлайн"
            r"|watch\b.{0,150}(online|episode|free\b)"
            r"|episode.{0,150}\bsub\b",
            title=True, body=False, username=True,
            max_rep=32, max_score=1)
```
