### ISSUE TITLE
Let Smokey take commands as SD

### ISSUE THREAD

**Issue by Daniil-M-beep** [Charcoal-SE/SmokeDetector#4083]
Currently, Smokey takes commands with `!!/` and `sd` for aliases, e.g. `k` etc.

Can we let Smokey take all `sd` commands? For me, this is much easier and quicker to type, especially on mobile.

e.g.:

`sd watch test`

`sd approve 1000`

etc.

**Comment by NobodyNada** [comment]
I'm not saying that we should or shouldn't do this, but there are some complexities we do need to take into account. `sd` commands have different semantics than `!!/` commands (see [Shortcut commands](https://charcoal-se.org/smokey/Commands#shortcut-commands)). The `sd` shorthand is used to invoke commands that operate on chat messages (such as `k`, `f`, `delete`), while `!!/` is used to invoke global commands such as `!!/watch` or `!!/reboot`. Invoking a command using `sd` syntax is shorthand for replying to Smokey's most recent chat message.

The tricky bit is that `sd` syntax allows you to specify multiple commands on one line. For example, `sd k 2f - delete` would mark the most recent message as a TP, mark the second- and third- most recent messages as FPs, skip the fourth, and delete the fifth-most recent message. Because of this, commands written with `sd` syntax cannot take parameters; e.g. `sd watch test` would be interpret `watch` and `test` as two separate commands.

There may be ways around this challenge -- perhaps we could recognize non-reply commands such as `watch` and bypass the normal shorthand command logic -- but adding another special case would make shorthand command syntax a bit convoluted and harder to learn, and there might be additional edge cases I haven't thought of.

**Comment by Daniil-M-beep** [comment]
Implemented: https://github.com/Charcoal-SE/SmokeDetector/pull/4096
