### ISSUE TITLE
Delay role is still posting reports even if the posts are deleted

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#5046]
The `delay` role for a room is supposed to delay posting of a message for five minutes after a report, and not post about it if it gets deleted or marked as a false positive during that delay.

However, I've noticed that today, it's now still posting those reports after the 5-minute delay, even if they were deleted during that time. (I don't have a case of a post that was marked as a false positive, so I don't know if it's an issue for that as well.)

Can that functionality please be restored?

**Comment by makyen** [comment]
This appears to be a problem with SE WebSockets. Please see: [2020-10-13 (3rd time): Random pages across SE feel “dead”, due to SE WebSocket misbehaving: sometimes connecting, sending heartbeat, but no data](https://meta.stackexchange.com/questions/355324/2020-10-13-and-again-3rd-random-pages-across-se-feel-dead-due-to-se-websoc).
