### ISSUE TITLE
FR: Make SmokeDetector's "tpu- by <name>" message reply to the report.

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/SmokeDetector#573]
Just a small eye-candy modification:

I'd like to see SmokeDetector's feedback responses reply to the report the feedback is applied to.
This will allow chat's message highlighting / navigation to link between the report and it's feedback.
Especially practical for the feedback messages for older reports, or cases like this:

![capture](https://cloud.githubusercontent.com/assets/2911988/23788946/1f05867a-0579-11e7-850c-7b68767229eb.png)

**Comment by ArtOfCode-** [comment]
We don't have the data to do this with, and it doesn't seem like it's really worth getting it for something this small. The `tpu- by <name>` messages are sent from metasmoke to Smokey via a websocket. metasmoke doesn't know the message ID that the report is in, so it can't add it to the message; Smokey can't either because those messages aren't the only thing that comes down the socket, and other messages don't need to be replies.

**Comment by Cerbrus** [comment]
I was hoping a message Id was stored somewhere, but since that's not the case, I agree with _"doesn't seem like it's really worth getting it"_. Too much effort for too little gain.
