### ISSUE TITLE
User blacklisted after vandalism feedback

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#574]
[This user](http://gis.stackexchange.com/u/86327) was [blacklisted](http://m.erwaysoftware.com/posts/by-url?url=//gis.stackexchange.com/a/231586), after Cerbrus and I reported vandalism/tp- on [this report](http://m.erwaysoftware.com/posts/by-url?url=//gis.stackexchange.com/questions/229140).

**Comment by angussidney** [comment]
Currently, Metasmoke doesn't differentiate between `tpu-` and `tp-`, since it identifies each feedback by the first letter. There haven't been any use cases for a differentiation between the feedbacks until FIRE came around, so that's why it is like it is currently.

As you can see [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/metasmoke.py#L86), MS will always tell Smokey to blacklist a user when it receives FP feedback.

This probably should be fixed, and when it gets fixed, `/review` shoud also be updated to give `tpu-` feedback instead of `tp-`.

**Comment by Glorfindel83** [comment]
But we do want to be able to give `tp-` feedback from /review when it's vandalism. We need four buttons then, just like FIRE (three when it's a question).

**Comment by Glorfindel83** [comment]
In [this instance](https://chat.stackexchange.com/transcript/message/36304124#36304124), a user was blacklisted after an `naa-` feedback.

**Comment by NobodyNada** [comment]
This has been fixed in Metasmoke: https://github.com/Charcoal-SE/metasmoke/commit/9ec4e350406181120554e584738947fa301c3ebd
