### ISSUE TITLE
Don't send Smokey reports to rooms that are on a delay if the post is already deleted

### ISSUE THREAD

**Issue by rschrieken** [Charcoal-SE/SmokeDetector#651]
I do know flagging is effective and posts gets deleted quickly. It turns out that the detection if a post is deleted doesn't seem to work correctly causing Smokey to send posts to for example the Tavern while the posts are already deleted. Example of such a batch starts here:

http://chat.meta.stackexchange.com/transcript/message/5949913#5949913

Can this be looked at and fixed, preferable in 6 to 8 weeks?

**Comment by AWegnerGitHub** [comment]
Example post:

MS Link: https://metasmoke.erwaysoftware.com/post/66304  (Notice: Post deleted after 200 seconds after being reported)
Charcoal Link: http://chat.stackexchange.com/transcript/message/36995938#36995938
Tavern link: http://chat.meta.stackexchange.com/transcript/message/5970319#5970319  

The tavern link was posted after the post was deleted.

**Comment by ArtOfCode-** [comment]
66304 is deleted, FYFI

**Comment by hichris1234** [comment]
Another example: http://chat.meta.stackexchange.com/transcript/message/5983910#5983910, https://metasmoke.erwaysoftware.com/post/66900.

**Comment by Undo1** [comment]
Deletion log on the one @hichris1234 posted came from the metasmoke API.

**Comment by angussidney** [comment]
Maybe we should be sending deletion logs back down the socket to Smokey?

**Comment by hichris1234** [comment]
Problem: https://github.com/Charcoal-SE/SmokeDetector/blob/master/deletionwatcher.py#L34-L37
Someone decided to change the link structure, which broke this for answers.

**Comment by hichris1234** [comment]
Broken via https://github.com/Charcoal-SE/SmokeDetector/commit/619decf12d278445688ce56c42be1952896297b2. question_id needed to be question_id there... which apparently is not a thing, because someone decided that question_id and answer_id are synonymous. Not quite.

**Comment by teward** [comment]
@hichris1234 `question_id` doesn't exist in the Post object.  `question_id` is actually stored in the individual Post object as `post_id` - if this isn't the case, then we need to look at the Post class, because every other place where question ID and answer ID exist are exchangeable, and if you look at the parsing code in Post, if it's an answer it stores the answer ID in the post id, if it's a question it stores the question id in the Post ID.  Failing that, we need to be then checking `post.is_answer` to determine whether it's an Answer ID or not.

This was done during the design process of the Post class; but it seems to me that the actual issue here isn't question ID vs. answer ID, it's a logic handler question.

The relevant parts are here:

From API Response processing:

        # Map response elements to the corresponding variable for the Post object internally.
        element_map = {
            'site': '_post_site',
            'link': '_post_url',
            'score': '_post_score',
            'up_vote_count': "_votes['upvotes']",
            'down_vote_count': "_votes['downvotes']",
            'owner': {
                'display_name': '_user_name',
                'link': '_user_url',
                'reputation': '_owner_rep'
            },
            'question_id': '_post_id',
            'answer_id': '_post_id'
        }

In the element mapping downstream:

        for (element, varmap) in element_map.items():
            try:
                if is_api_response and element == 'owner':
                    for (subelement, subvarmap) in element_map['owner'].items():
                        try:
                            self[subvarmap] = (html.unescape(data['owner'][subelement]) if subelement == 'display_name'
                                               else data['owner'][subelement])
                        except KeyError:
                            # Go to next subkey
                            continue
                    continue  # Go to next key because we're done processing the 'owner' key.

                # Other keys
                self[varmap] = data[element]
            except KeyError:
                # Executes if the 'element' requested isn't part of the response.
                continue  # Go to next key

This is all operable, and therefore *is* interchangeable because `post_id` in the Post object *should* always be a valid ID.  If it's not working here, then we need to analyze logic first to determine if it's an answer type or not (this is what the post.is_answer property is for)

**Comment by Undo1** [comment]
@angussidney's suggestion is probably a good idea anyway. Gives us two chances to get data instead if just one.

**Comment by hichris1234** [comment]
@teward In that code, it needs the parent question ID. I don't know what the Post object does, but it isn't giving the parent question ID for answers. Somehow that needs to be fixed, because DeletionWatcher *isn't checking answers at all anymore* because the websocket relies only on question IDs.

**Comment by teward** [comment]
@hichris1234 Then in that case it's `post.parent.post_id`, because we now store parent objects as their own Post objects.

**Comment by teward** [comment]
Let's see if that change fixes it; if it does we're good to go then.

**Comment by AWegnerGitHub** [comment]
Has this been resolved?

**Comment by AWegnerGitHub** [comment]
It's been 16 days and I haven't seen a complaint. I'm going to close this.
