### ISSUE TITLE
MS websocket get broken/disconnected after blacklisting 2 items

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/SmokeDetector#652]
After blacklisting 2 things quickly after each other, the MS websocket doesn't respond any post feedback messages, and also doesn't show the CI status anymore

Examples of this problem:

* https://chat.stackexchange.com/rooms/11540/conversation/ms-break-1
* https://chat.stackexchange.com/rooms/11540/conversation/ms-break-2

**Comment by tripleee** [comment]
It's not particularly quickly even (dunno if that's visible from the transcript) but I'm guessing it needs a critical region to prevent an incoming one from messing up another which is in progress ... or refactoring to make this a non-issue. (Pure speculation though; it's been a while since I looked at the code, though I remember working on a fix for similar issues a few months back, but then getting distracted.)

**Comment by tripleee** [comment]
https://github.com/Charcoal-SE/SmokeDetector/issues/679 is closed but still happening.

**Comment by ArtOfCode-** [comment]
Is this still an issue?

**Comment by ferrybig** [comment]
Yes, examples:

* 1 day ago: https://chat.stackexchange.com/transcript/11540?m=37825203#37825203
* 4 days ago: https://chat.stackexchange.com/transcript/message/37755964#37755964
* 5 days ago: https://chat.stackexchange.com/transcript/message/37720318#37720318 (scroll a bit up at this one and you see its caused by 2 repeated watch keywords commands

**Comment by angussidney** [comment]
Has this been recently reproduced?
