### ISSUE TITLE
Error linking to SmokeDetector notice in chat for feedback

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#673]
It seems that linking back to a Smokey notice in chat for feedback gets resolved to the latest feedback to the post in question, so you can end up providing incorrect feedback for a post which has been edited.

For example, I posted feedback to vandalism which had been reverted.  The rollbacks were also posted to chat because the user was blacklisted.  Now, even though I specifically linked to the notices for the vandalized posts, the feedback was posted to the rollbacks.

Transcript: http://chat.stackoverflow.com/transcript/message/36808532#36808532

I have not removed my feedback from the posts so that the evidence is still there if you should need it.

**Comment by teward** [comment]
So, if a post is edited, you're saying it gets a duplicate record, and somehow the feedback can be given back to the wrong MS record?  (It's unclear what exactly you're referencing...)

**Comment by ArtOfCode-** [comment]
@teward Imagine:

 - Message 1: SmokeDetector report of post A. Post A is a tpu.
 - Message 2: tpu- by User A
 - Message 3: SmokeDetector report of post A, for the second time because it got caught again. Requires different feedback this time, say fp-.
 - Message 4 (reply to 1), by User B: tpu-

User B's tpu- is now attached to the *second* report of Post A in metasmoke.

**Comment by tripleee** [comment]
Yes, exactly.  Should I update the problem description or is this sufficient?
