### ISSUE TITLE
Chat restart loop when quota updated

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#7032]
### What problem has occurred? What issues has it caused?

SmokeDetector started emitting "API quota rolled over" messages around here:

https://chat.stackexchange.com/transcript/message/61229826#61229826

Based on comments from Cody I tried to update the number in `bodyfetcher.py` to reflect my best guess as to what that number should be.

It's probably too early to say, but it looks like things got more quiet after this commit:
https://chat.stackexchange.com/transcript/message/61230233#61230233

### What would you like to happen/not happen?

Ideally, the number should probably not be hardcoded as long as the quota is subject to change. Is there some way we could infer from the current value what it actually is, or at least some way we can avoid emitting the same message very frequently?

Equally ideally, when the quota changes, we should be notified, and coordinate with whoever implements that change.

As a fallback, perhaps at least document the logic in there slightly more, to help us understand what it's checking for, and under what circumstances the number could change, and then how we would decide what to change it to.

**Comment by codygray** [comment]
Fixed by @makyen in https://github.com/Charcoal-SE/SmokeDetector/commit/20520b448e, along with constants to hopefully increase the clarity of the logic for future maintainers.

**Comment by makyen** [comment]
The reason we get lots of messages and why we have non-trivial logic for quota rollover detection is that the current number of requests, the rollover time, and the max quota numbers are all stored separately on SE's different chat servers. From time to time, the numbers for those get out of sync on the different servers and can report unexpected values. The servers do, eventually, sync up, but sometimes it takes a while. On some occasions, it's even required SE to perform manual operations to cause a re-sync.

As a result of this, in order to not be spewing out lots of "rollover" messages under semi-normal operation, in order to report a rollover, we require the reported `quota_remaining` to be above a known threshold that's *close* to the maximum quota which we have *and* for there to be a substantial increase in the `quota_remaining` property value from the last one which we've seen . That works most of the time to prevent spurious "rollover" messages.

The logic doesn't work for the case where our maximum quota is increased *and* where SE's servers aren't in semi-close sync. The bunch of "rollover" messages were created because the `quota_remaining` would be different by many thousands of requests, depending on which SE API server SD was talking to *and* the maximum reported was above the threshold we were using to detect an *actual* rollover event. So, we'd get several `quota_remaining` values in the 66k ballpark, then one or more in the 25k ballpark, and then back to the 66k ballpark (which is then detected as a rollover event). That happened many times.

Our max quota increasing is a quite rare event, so we haven't increased the complexity of the logic to try to account for times when that happens. We can make that detection more complicated. I probably should have done so prior to this most recent increase, but I chose not to expend that time. In retrospect, doing so, probably, would have saved time overall. At this point, we're not really expecting another increase any time soon, so *right now* the benefit of doing that is small.
