### ISSUE TITLE
Don't report Staging Ground posts to other rooms than CHQ

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#7649]
### Is your feature request related to a problem? Please describe.

https://m.erwaysoftware.com/posts/uid/stackoverflow/75721102 was reported in SOCVR. One of the participants in the room was surprised that they were unable to visit the post. https://chat.stackoverflow.com/transcript/message/56097157#56097157

### Describe the solution you'd like

My proposal would be to not report Staging Ground posts to other rooms, but I suppose an alternative could be to clearly mark them up to identify them as Staging Ground posts. (This would be attractive for other reasons as well.)

### Additional context

Many users do not have access to the Staging Ground, and so reporting posts that they cannot access or assess seems like a waste of their time.

**Comment by codygray** [comment]
I [partially] disagree with this. Staging Ground posts are *specific* to Stack Overflow; thus, it makes sense to report them in SO-specific chat rooms, including SOCVR (unless the SOCVR room owners specifically object, which I have not seen evidence of). If anything, it's actually more likely that lurkers in SO-specific chat rooms will have access to the SG than it is lurkers in CHQ will have access to it.

Of course, I'd have no objection to clearly indicating that the posts are from the Staging Ground in the message itself.

**Comment by makyen** [comment]
Overall, working on this made quite a bit more sense when Staging Ground was in private beta, which was when this was proposed. After this was proposed, but prior to it being implemented, the company shut down the Staging Ground private beta. When the Staging Ground returned, about a year later, it was directly released publicly. There were, initially, significant issues with access, because the requirements for access were, initially >= 500 reputation *and* having posted >= 2 well received questions. That was changed after a couple of weeks to only requiring >= 500 reputation, which is similar to the first review queues on SO.

Now that the Staging Ground is public and the requirement for viewing Staging Ground posts is only >= 500 reputation, I feel that this is, at best, a low priority.

* I do object to a blanket "don't show".  
* I don't object to each room having the option to not show them, similar to how a room can be configured to show or not show experimental reasons.
* I don't object to indicating that such posts are in the Staging Ground, but someone not being able to view the post on the site is *vastly* less of a problem than it was when Staging Ground was in a private beta and only very few people were able to view the posts.

**Comment by codygray** [comment]
Given what @makyen already said, combined with the fact that these posts have been being reported everywhere since the public re-launch of the Staging Ground without any complaints that I've seen, I think we can close this.

Like Makyen, I don't necessarily object to giving each room an option to opt-out of showing Staging Ground posts, especially as they are Stack Overflow-only. They need to always be shown in Charcoal HQ, but it would be reasonable for other rooms to be able to opt out of them. However, given the apparent lack of demand for this feature, and the extremely marginal benefits, it seems, in my judgment, hardly worth doing.

If someone strongly objects, please comment with an argument in favor and we can re-open!

The still-relevant portion of this feature request for me is to clearly indicate that posts being reported are coming from the Staging Ground. This was previously part of a PR (linked above). I have created [a new issue](https://github.com/Charcoal-SE/SmokeDetector/issues/13136) for tracking that.
