### ISSUE TITLE
Require less strict privileges for `!!/watch-keyword`

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#796]
The `!!/watch-keyword` command poses less of a security risk than `!!/blacklist-*`, and should therefore not require `codeadmin` privileges as it does now; just `reviewer` should suffice. Thoughts?

**Comment by angussidney** [comment]
As long as it has a reason weight of 1 or 0 (which looks to be the case) and it doesn't report outside of CHQ (I think tripleee had a try of this a while ago, but I'm not sure whether or not it's worked properly or not), it's a thumbs up from me.

**Comment by tripleee** [comment]
The PR was sitting in review but I merged it now. I'll try to come up with a test case.

**Comment by ArtOfCode-** [comment]
Has this been done, then?

**Comment by tripleee** [comment]
No; the Charcoal-only requirement (which I had a fix for) and the weight pinning are done, but this still requires somebody to approve a PR if somebody who isn't a code owner attempts to watch something. Turnaround has improveo, but I would not be surpried if approval times average in hours rather than minutes.
