### ISSUE TITLE
No chat messages for reports via FDSC

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#939]
As mentioned [here](https://github.com/Charcoal-SE/metasmoke/issues/200), reports via FDSC are correctly received by metasmoke. However, Smokey doesn't post them in chat and doesn't create a 'real' report in metasmoke. I assume those two are related. Probably, the websocket is broken.

**Comment by angussidney** [comment]
I've tested this, and Smokey appears to be throwing this error:

```
[10:45:19] 'NoneType' object has no attribute 'post_id'
Traceback (most recent call last):
  File "/home/ubuntu/charcoal/SmokeDetector/metasmoke.py", line 47, in init_websocket
    Metasmoke.handle_websocket_data(data)
  File "/home/ubuntu/charcoal/SmokeDetector/metasmoke.py", line 126, in handle_websocket_data
    why=why)
  File "/home/ubuntu/charcoal/SmokeDetector/spamhandling.py", line 101, in handle_spam
    datahandling.add_post_site_id_link((post.post_id, post.post_site, "answer"), post.parent.post_id)
AttributeError: 'NoneType' object has no attribute 'post_id'
```

**Comment by j-f1** [comment]
The issue here seems to be that the post doesn’t get its `parent` set, even though it’s an answer.

**Comment by teward** [comment]
Is this still an issue, because I don't see this happening right now on Lunar Eclipse.  And it's been up for a better part of a day now (after @angussidney's decided to stuff itself with the SSH key issue).

Can we get some examples of such posts which are related to this?

**Comment by angussidney** [comment]
To test @j-f1's theory, [I tried to report a question](https://chat.stackexchange.com/transcript/message/40174113#40174113), and it worked perfectly.

@teward this is an issue that is only occurs when an answer is reported via the MS API, not during normal operation. To reproduce, simply try reporting any answer via the API. I've tested it on your instance, and the issue is still occuring.

**Comment by teward** [comment]
If this is only happening when the MS API is the only report source then perhaps we should start by looking at what is sent by MS to Smokey to process this (@Undo).  Because I’m not sure we have a mechanism to specifically handle MS API reports differently from standard posts.



*Sent from my iPhone.  Please excuse any typos, as they are likely to happen by accident.*

**Comment by angussidney** [comment]
[[status-fixed]](https://chat.stackexchange.com/transcript/message/40231680#40231680) by 70b9796

This was caused by a simple misspelling on [this](https://github.com/Charcoal-SE/SmokeDetector/blob/a2c9ec2f2a354e0dc5af2d3110d5a8587d2e07f8/metasmoke.py#L119) line, where CamelCase was used instead of snake_case ([as should be the case](https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommands.py#L1410)). The `Post()` constructor was therefore considering all answers to be questions, due to the missing `is_answer` attribute, causing the `parent` attribute to also be absent, causing issues further down the line.
